name: base
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - jupytext==1.5.0
  - nbdime==2.0.0
  - libgcc==7.2.0
  - libgcc-ng==9.1.0
  - r-base==3.6.1
  - r-devtools==2.0.2
  - r-biocmanager==1.30.4
  - papermill==2.1.0
  - r-git2r==0.27.1
  - r-r.oo==1.23.0
  - r-stringr==1.4.0
  - r-dorng==1.8.2
  - r-statmod==1.4.34
  - r-foreach==1.5.0
  - r-foreach==1.5.0
  - r-r.utils==2.9.2
  - r-devtools==2.0.2
  - r-irkernel==1.1
  - r-pheatmap==1.0.12
  - r-snakecase==0.11.0
  - r-doparallel==1.0.15
  - r-data.table==1.12.8
  - r-tibble==2.1.3
  - r-rlang==0.4.6
  - r-downloader==0.4
  - r-dbi==1.1.0
  - r-readr==1.3.1
  - r-r.methodss3==1.8.0
  - r-gprofiler2==0.1.9
  - bioconductor-edger==3.28.0
  - bioconductor-limma==3.42.0
  - bioconductor-biobase==2.46.0
  - bioconductor-multtest==2.42.0
  - bioconductor-biomart==2.42.0
  - r-statmod==1.4.34
  - r-ggplot2==3.3.2
  - r-ggsci==2.9
  - r-coda==0.19_3
  - r-rstan==2.19.3
  - r-rjags==4_10
  - r-compute.es==0.2_5
  - bioconductor-rtracklayer==1.46.0
  - bioconductor-biostrings==2.54.0
